forefront/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from projects.views import (HomeView, 
        LabsView, AuthorView, CreateView, LoginView, 
        SignupView, ProfileView, LabView, ProjectView, 
        SearchView, UploadView, LogoutView, MemberAutocompleteView, 
        PreviewView, AuthorCreate, LikesView, GetUniversityListView, 
        signup, activate, account_activation_sent,
        new_lab_users_list, new_lab_user_action, ProjectEditView, 
        # LabUploadView, 
        LabPreviewView, LabEditView, DeleteCommentAjaxView, ProfessorAutocompleteView,
        AuthorAutocompleteView, UniversityAutocompleteView, RemoveSessionsView, search_paginate_view, search_paginate_json_view, search_paginate_projects_view, search_paginate_groups_view, search_paginate_members_view, UserInvitationView
)
# SearchPaginationView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('labs/', LabsView.as_view(), name='labs'),
    path('author', AuthorCreate.as_view()),
    path('author/<int:pk>', AuthorView.as_view(), name='author'),
    path('create', CreateView.as_view(), name='create'),
    path('lab/<int:pk>', LabView.as_view(), name='lab'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    #path('signup', SignupView.as_view(), name='signup'),
    path('account_activation_sent/', account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',activate, name='activate'),
    path('signup/', signup, name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project'),
    path('search', SearchView.as_view(), name='search'),
    path('upload/', UploadView.as_view(), name='upload'),
    path('upload/<int:id>/',ProjectEditView.as_view(), name="project-edit"),
    # path('lab/upload/', LabUploadView.as_view(), name='lab_upload'),
    path('lab/preview/', LabPreviewView.as_view(), name='lab_preview'),
    path('lab/edit/<int:pk>/', LabEditView.as_view(), name='lab_edit'),    
    path('preview/', PreviewView.as_view(), name="preview"),
    path('authors-autocomplete', AuthorAutocompleteView.as_view(), name='authors-autocomplete'),
    path('members-autocomplete', MemberAutocompleteView.as_view(), name='members-autocomplete'),
    path('professors-autocomplete', ProfessorAutocompleteView.as_view(), name='professors-autocomplete'),
    path('university-autocomplete', UniversityAutocompleteView.as_view(), name='university-autocomplete'),
    path('likes/', LikesView.as_view(), name='likes'),
    path('university-list/', GetUniversityListView.as_view(), name='university-list'),
    path('new-lab-users-list/', new_lab_users_list, name='new_lab_user'),
    path('new-lab-user/<str:action>/<int:user_id>/', new_lab_user_action, name='new_lab_user_action'),
    path('delete-comments-ajax/', DeleteCommentAjaxView.as_view(), name='delete-comments-ajax'),
    path('remove-sessions/', RemoveSessionsView.as_view(), name='remove-sessions'),
    path('search-paginate/', search_paginate_view, name='search-page'),
    path('search-paginate-json/', search_paginate_json_view, name='search-page-json'),
    path('search-paginate-projects/<str:search_data>/', search_paginate_projects_view, name='search-page-projects'),
    path('search-paginate-groups/<str:search_data>/', search_paginate_groups_view, name='search-page-groups'),    
    path('search-paginate-members/<str:search_data>/', search_paginate_members_view, name='search-page-members'),
    path('invite/', UserInvitationView.as_view(), name='invite'),
    
    # path('save-author/', SaveAuthorView.as_view(), name='saveauthor'),
] 


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.db.models.fields import CharField, TextField, DateField, EmailField, URLField, IntegerField
from django.db.models import ImageField
from django.contrib.auth.models import User
from django.contrib.staticfiles.templatetags.staticfiles import static

class CustomUser(models.Model):
    USER_TYPES = [
        ('SU', 'Student'),
        ('LA', 'Lab Admin'),
        ('PF', 'Professor'),
    ]

    USER_IS_APPROVED = 1
    USER_IS_NOT_APPROVED = 0

    # Reference to the User model
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    # The type of student
    #   SU - Student
    #   LA - Lab Admin
    #   PF - Professor
    type = models.CharField(
        max_length = 2,
        choices=USER_TYPES,
        default='SU',               # Default is Student
    )
    status = models.IntegerField(default=USER_IS_NOT_APPROVED)  # 0 - Not approved
                                                                # 1 - Approved

    # def __str__(self):
    #     return self.user


class Member(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    first_name = CharField(max_length=50)
    last_name = CharField(max_length=50)
    image = ImageField(null=True, blank=True, max_length=255)
    position = TextField(blank=True)
    ideal_role = TextField(blank=True)
    education = TextField(null=True, blank=True)       # no use for upload page
    website = URLField(blank=True)
    # email = EmailField(blank=True)
    main_lab = models.ForeignKey("Lab", on_delete=models.SET_NULL, null=True)   # no use for upload page
    university = models.ForeignKey("University", on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.first_name + " " + self.last_name

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        return static('projects/images/default.png')



class University(models.Model):
    name = CharField(max_length=50, null=True)
    class Meta:
        verbose_name_plural = "universities"
    def __str__(self):
        return self.name

class MemberQualification(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    degree = models.CharField(max_length=50)
    year = models.IntegerField()

class MemberWorkExperience(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    company = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    yearfrom = models.IntegerField()
    yearto = models.IntegerField()


class Project(models.Model):
    image = ImageField(null=True, max_length=255)   # banner image
    excerpt = TextField(null=True)
    body = TextField()
    name = CharField(max_length=200)
    authors = models.ManyToManyField(Member)
    likes = IntegerField(default=0)
    lab = models.ForeignKey("Lab", on_delete=models.SET_NULL, null=True)
    image1 = ImageField(null=True, max_length=255, blank=True)
    image2 = ImageField(null=True, max_length=255, blank=True)
    image3 = ImageField(null=True, max_length=255, blank=True)
    created_date = models.DateField(auto_now_add=True)
    nature_contribution = models.CharField(null=True,max_length=200)    # disabled this field for now.
    def __str__(self):
        return self.name
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        return static('projects/images/default.png')

    def image1_url(self):
        if self.image1 and hasattr(self.image1, 'url'):
            return self.image1.url
        return None

    def image2_url(self):
        if self.image2 and hasattr(self.image2, 'url'):
            return self.image2.url
        return None

    def image3_url(self):
        if self.image3 and hasattr(self.image3, 'url'):
            return self.image3.url
        return None

class MemberProjectComment(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    comment = TextField()
    is_owner = IntegerField(default=0, null=True)


class Lab(models.Model):
    owner   = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='labs', null=True, blank=True)
    name = CharField(max_length=200)
    image = ImageField(null=True)
    professors = models.ManyToManyField(Member, related_name='professors')
    members = models.ManyToManyField(Member, related_name='members')
    excerpt = TextField(blank=True, null=True)
    university = models.ForeignKey("University", on_delete=models.SET_NULL, null=True)
    major_contributions = TextField(blank=True, null=True)
    sources_of_funding = TextField(blank=True, null=True)
    def __str__(self):
        return f"{self.name} ({self.university})"
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        return static('projects/images/7cb07f_db9a29e4c52744729b8cb99f1a87dc05-mv2.jpg')

class LabResearchTopic(models.Model):
    name = CharField(max_length=200)
    image = ImageField(null=True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    excerpt = TextField(blank=True, null=True)
    def __str__(self):
        return self.name
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        return static('projects/images/7cb07f_db9a29e4c52744729b8cb99f1a87dc05-mv2.jpg')

class LabPublication(models.Model):
    date = DateField(auto_now_add=True)
    citation = TextField()
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-date']
    def __str__(self):
        return f"{self.date}: {self.lab}"


class Userlikes(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    like = IntegerField(default=0)

projects/forms.py
from dal import autocomplete,forward
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Member, University, MemberProjectComment, Project
from random import choice
from string import ascii_lowercase, digits
from django.conf import settings
from django.db.models import Q
import re
# ModelSelect2Multiple
class AuthorForm(forms.ModelForm):
    author_select = forms.ModelChoiceField(
        queryset=Member.objects.filter(Q(user__type='SU')| Q(user__type='PF')),
        widget=autocomplete.ModelSelect2Multiple(url='authors-autocomplete', attrs={'data-html': True}, forward=None),
    )
    authors = forms.ModelChoiceField(
        queryset=Member.objects.filter(Q(user__type='SU')| Q(user__type='PF'))
    )
    class Meta:
        model = Member
        fields = ('__all__')


class ProjectForm(forms.ModelForm):
    author_select = forms.ModelChoiceField(
        queryset=Member.objects.filter(user__type='SU'),
        widget=autocomplete.ModelSelect2Multiple(url='members-autocomplete', attrs={'data-html': True}),
    )
    authors = forms.ModelChoiceField(
        queryset=Member.objects.filter(user__type='SU')
    )
    class Meta:
        model = Member
        fields = ('__all__')

class UniversityForm(forms.ModelForm):
    university_select = forms.ModelChoiceField(
        queryset=University.objects.all(),
        widget=autocomplete.ModelSelect2(url='university-autocomplete', attrs={'data-html': True}),
    )
    universities = forms.ModelChoiceField(
        queryset=University.objects.all()
    )
    class Meta:
        model = University
        fields = ('__all__')


class ProfessorForm(forms.ModelForm):
    prof_select = forms.ModelChoiceField(
        queryset=Member.objects.filter(user__type='PF'),
        widget=autocomplete.ModelSelect2Multiple(url='professors-autocomplete', attrs={'data-html': True}, forward=None),
    )
    prof = forms.ModelChoiceField(
        queryset=Member.objects.filter(user__type='PF')
    )
    class Meta:
        model = Member
        fields = ('__all__')

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

def generate_random_username(length=16, chars=ascii_lowercase+digits, split=4, delimiter='-'):

    username = ''.join([choice(chars) for i in range(length)])

    if split:
        username = delimiter.join([username[start:start+split] for start in range(0, len(username), split)])

    try:
        User.objects.get(username=username)
        return generate_random_username(length=length, chars=chars, split=split, delimiter=delimiter)
    except User.DoesNotExist:
        return username;

class SignUpForm2(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not settings.DEBUG:
            # regex = '^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*\.(edu)$'
            regex = r'[a-zA-Z0-9._-]+@[a-zA-Z0-9-]+\.(edu)'
            if re.search(regex,email) :
                print("Valid Email")
                return email
            else:
                print("Invalid")
                raise forms.ValidationError("Please, Enter an .edu email!")
        else:            
            return email

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.username = generate_random_username()
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()

        return user


# class ProductForm(ModelForm):
#     class Meta:
#         model = Product
#         exclude = ('updated', 'created')

#     def __init__(self, args, *kwargs):
#         super(ProductForm, self).__init__(*args, **kwargs)
#         self.fields['description'].widget = TextInput(attrs={
#             'id': 'myCustomId',
#             'class': 'myCustomClass',
#             'name': 'myCustomName',
#             'placeholder': 'myCustomPlaceholder'})


class LabAdminUserForm(forms.Form):
    lab_name    = forms.CharField(label="Lab Name", max_length=255)
    university  = forms.ModelChoiceField(label="University", 
                    queryset=University.objects.order_by('name'), 
                    empty_label="---------------------"
                )

class UserInvitationForm(forms.Form):
    email = forms.EmailField(label="Email",widget=forms.TextInput(attrs={'placeholder': 'Email'}), required=True)
    projects = forms.ChoiceField(required=True)    

    class Meta:
        fields = ('email', 'projects')

    def clean_email(self):
        print('herere1')
        email = self.cleaned_data['email']
        is_email_exist = User.objects.filter(email=email)
        if is_email_exist:
            print('ddd')
            raise forms.ValidationError('Email already exists.')
        if email:
            raise forms.ValidationError('Please check email field.')
        return email

    def clean_projects(self):
        project_id = self.cleaned_data['projects']
        print('project_id')
        print(project_id)
        is_project_exist = Project.objects.filter(id=project_id)
        if not is_project_exist:
            raise forms.ValidationError('Selected Project does not exist..')
        if project_id:
            raise forms.ValidationError('Please check projects field.')
        return project_id    



    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        member_id = request.user.customuser.member.id
        project_ids = list(MemberProjectComment.objects.filter(member_id=member_id).values_list('project_id', flat=True))
        projects_arr = list(Project.objects.filter(id__in=project_ids).values_list('id','name'))
        projects_arr.insert(0, [None,'Select Project'])
        self.fields['projects'].choices=projects_arr

projects/templates/projects/_lab_topic_slider.html
<div id="{{id}}" class="carousel slide groups" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    {% for item in list %}
    <div class="item {% if forloop.counter0 == 0 %}active{% endif %}" id="slide{{forloop.counter}}">
      <div style="height: 500px; width: 100%; overflow: hidden;">
        <img src="{{item.image_url}}" alt="" style="width: 100% !important; height: 100%; border-radius: 0 !important;">
      </div>
      <div class="carousel-caption">
        <h1>{{item.name|capfirst}}</h1>
        <hr class="carousel">
        <p class="lead">{{item.excerpt|capfirst}}</p>
      </div>
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#{{id}}" role="button" data-slide="prev">
    <svg version="1.1" class="prev" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
      x="0px" y="0px" viewBox="0 0 21 41" enable-background="new 0 0 21 41">
      <polygon points="20.3,40.8 0,20.5 20.3,0.2 21,0.9 1.3,20.5 21,40.1 "></polygon>
    </svg>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#{{id}}" role="button" data-slide="next">
    <svg version="1.1" class="next" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
      x="0px" y="0px" viewBox="0 0 21 41" enable-background="new 0 0 21 41">
      <polygon points="20.3,40.8 0,20.5 20.3,0.2 21,0.9 1.3,20.5 21,40.1 "></polygon>
    </svg>
    <span class="sr-only">Next</span>
  </a>
  <ol class="carousel-indicators hidden-xs">
    {% for item in list %}
    <li data-target="#{{id}}" data-slide-to="{{forloop.counter0}}" class="active"></li>
    {% endfor %}
  </ol>
</div>

projects/templates/projects/_resume.html
{% load static %}
{% comment %} <div class="row resume-container">
    <div class="author-inner">
        <div class="author-profile-info">
            <div class="group-lead-container">
                <h5>Ideal Role</h5>
                {% if not edit %}
                <div class="forefront-whitespace">{{object.ideal_role}}</div>
                {% else %}
                <div contenteditable class="forefront-whitespace">{{object.ideal_role|default:"describe your ideal role"}}
                </div>
                {% endif %}
                <h5>Previous Work Experience</h5>
                {% if not edit %}
                <div class="forefront-whitespace">{{object.ideal_role}}</div>
                {% else %}
                <div contenteditable class="forefront-whitespace">{{object.ideal_role|default:"describe your ideal role (150 words max)"}}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div> {% endcomment %}




<script src="https://kit.fontawesome.com/9705adc575.js"></script>
    <!--CSS SECTION copy this to your CSS style file-->
    <style>

    /*Author section CSS Code*/
    .author_brief {
      height: 35vh;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #000000;
      color: white;

      border-style: solid;
      border-color: #CBC8BF;
    }

    .prof_main {
      display: flex;
      padding-left: 30%;
      justify-content: center;
      align-items: flex-start;
      flex-direction: column;
    }

    .fa {
      color: #CBC8BF;
    }

    .prof_sub {
      display: flex;
      padding-left: 30%;
      justify-content: center;
      align-items: flex-start;
      flex-direction: column;
    }

    .p_image {
      border-radius: 50%;
      border-color: #CBC8BF;
    }

    /*Author Details CSS Code*/
    .details {
      display: flex;
      justify-content: center;
      align-items: flex-start;
      flex-direction: column;
      background-color: #353535;
      color: white;

    }
    .fas {
      color: #CBC8BF;
      padding-left:5px;
    }
    .role {
      color: #FED501;
    }
    .work {
      color: #FED501;
    }

    .col-centered {
        text-align:left;
    }

    .work_list {
        list-style:None;
    }
    .entry {
      padding: 0 0 29px 0;
      width: 100%;
    }
    .ideal {
      padding:0;
    }
    .prev_work {
      padding:10px 0 10px 0;
    }

    </style>



      {% comment %}<!--- The Author Information Section --->
      <div class="author_brief">
        <div class="profile">
          <!-- Put link to profile image in this section -->
          <img class="p_image" border="5" src="https://via.placeholder.com/150/0000FF/808080/?text=Profile" alt="">
        </div>
        <div class="profile_brief">
          <!--Author main info-->
          <div class="prof_main">
            <span class="name">{Inser name here}</span>
            <span class="main_qual">{Insert main qualification here}</span>
            <span class="main_uni">{Insert main qualification university}</span>

            <!--Links-->
            <div class="links">
              <a href="mailto:{email}"><i class="fas fa-envelope"></i></a>
              <a href="{link to research page}"><i class="fas fa-microscope"></i></a>
              <a href="{page url}"><i class="fas fa-share-alt"></i></a>
            </div>
            <!--end of Links-->
          </div>
          <div class="prof_sub">
            <hr width=250px color="#bda00f">
            <!-- Use a for loop in this section -->
            <span class="sub_qual">{Inser qualification here}</span>
            <span class="sub_qual">{Inser qualification here}</span>
          </div>
        </div>
      </div>{% endcomment %}
      <!--- END OF The Author Information Section -->

      <!--- The Author Information Section -->
      <div class="col-md-12 style_bg" style="background-color:#353535">
      <div class="col-md-2"></div>
      <div class="col-md-8 row">
      <div class="col-md-3"></div>
      <div class="col-md-9" style="width:68.5%;">
        <div class="row">
          <div class="details">
            <div class="ideal ideal_role_style">
              <h3 class="role">Ideal Role</h3>
              {{ object.ideal_role }}
            </div>
          </div>        
        </div>
        {% if not user.customuser.type == 'PF' %}
        <div class="row">
          <div class="details">
            <div class="prev_work">
              <h3 class="work">Previous Work Experience</h3>
              <!-- Use a for loop in this section -->
                  
                    {% for exp in experience %}
                      <div class="entry">

                        <span class="company" style="float:left;">{{ exp.company }}</span>
                        
                        <span class="time"  style="float:right;">{{ exp.yearfrom }} - {{ exp.yearto }}</span>
                        <br>
                        <span class="postion"  style="float:left;">{{ exp.position }}</span>
                      </div>
                        {% empty %}
                        <span>No Experience Exist</span>
                      
                    {% endfor %}
                  
            </div>
          </div>        
        </div>
        {% endif %}
      </div>
        </div>
      </div>

projects/templates/projects/_search_list_item.html
<div class="row result">
    <!--<div class="col-md-2 col-sm-3 col-xs-12">
        <a href="{% url 'project' object.pk %}" title="{{project.title}}"><img src="{{object.image_url}}" alt="{{object.title}}"
                class="thumbnail-image"></a>
    </div>
    <div class="col-md-10 col-sm-9 col-xs-12">
        <h3 class="project-title"><a href="project.html">This: {{ object.name }}</a></h3>
        {% if objects.authors.all|length > 2 %}
            {% for author in object.authors.all %}
            <span class="author">{{author}}</span>
            {% endfor %}
        {% else %}
            <span class="author">{{ object.authors.all.0 }} and {{ object.authors.all.1 }}</span>
        {% endif %}
    </div>-->

    <div class="col-md-10">
        
        <p><a class="redirect_url" href="{% url 'project' object.pk %}" class="search_url">{{ object.name }}</a></p>
        
        <p class="search_item"></p>
        {% comment %} {% for author in object.authors.all %}
            {{author}}
        {% endfor %} {% endcomment %}
        
        </p>
        {% for single_member in object.memberprojectcomment_set.all %}
            <p>{% if single_member.is_owner == 1 %} <a class="redirect_url" href="{% url 'author' single_member.member_id %}"> {{ single_member.member.first_name }} {{ single_member.member.last_name }} (Owner)</a>{% endif %}</p>


            <p>{% if single_member.member.professors.all.count > 0 %}<a class="redirect_url" href="{% url 'author' single_member.member_id %}"> {{ single_member.member.first_name }} {{ single_member.member.last_name }} (Professor)</a>{% endif %}</p>
        {% endfor %}
    </div>
</div>

projects/templates/projects/_search_users_item.html
<div class="row result">
    <div class="col-md-2 col-sm-3 col-xs-12" style="padding: 0 0; margin-left:auto; margin-right: auto;">
        <a href="{% url 'author' object.pk %}" ><img src="{{ object.image_url }}" alt="{{ object.first_name }}"
                class="thumbnail-image thumbnail_img_style" ></a>
    </div>
    <div class="col-md-10 col-sm-9 col-xs-12">
        <!--<h3 class="project-title"><a href="project.html">This: {{ object.name }}</a></h3>-->

        <p class="search_term"><a class="redirect_url" href="{% url 'author' object.pk %}" >{{ object.first_name }} {{ object.last_name }}</a></p>
        <p class="search_term">{{ object.university.name }}</p>
    </div>
</div>

projects/templates/projects/account_activation_email.html
{% block content %}
{% autoescape off %}
Hi,

Please click on the link below to confirm your registration:

{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}
{% endblock %}

projects/templates/projects/author_create.html
{% extends 'projects/base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'projects/css/author_form.css' %}"/>
  <style type="text/css">
    .author-create-modal{
      margin-top: 40px;
    }
    .save-row{
      margin-bottom: 40px;
    }
  </style>
{% endblock %}
{% block content %}
<div class="container author-create-modal">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      {% include 'projects/author_form.html' %}
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'projects/js/author_form.js' %}"></script>
{% endblock %}

projects/templates/projects/index.html
{% extends "projects/base.html" %}
{% block bodyclass %}index{% endblock %}
{% load static %}
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="{% static 'projects/js/author_form.js' %}"></script>
{% endblock %}
{% block content %}
{% for object in zipped %}

{% include "projects/_project_list_item.html" with object=object index=forloop.counter0 %}

{% endfor %}

{% endblock %}

projects/templates/projects/signup.html
{% extends "projects/base.html" %}

{% block content %}
  <div class="col-sm-4">
    <h2 class="confirm-email-text" style="color: #e8e6e6; font-size: 14px !important;">{{ issue }}</h2>
  </div>
{% endblock %}

projects/templates/projects/test.html
{% extends "projects/base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            {% for object in object_list %}
    
            {% include "projects/_search_list_item.html" with object=object %}
    
            {% endfor %}
        </div>
        <div class="col">
            {% for object in object_list %}
    
            {% include "projects/_search_list_item.html" with object=object %}
    
            {% endfor %}
        </div>
        <div class="col">
            {% for object in object_list %}
    
            {% include "projects/_search_list_item.html" with object=object %}
    
            {% endfor %}
        </div>
    </div>
    
</div>

{% endblock %}